version: '3.7'

services:
    app:
        container_name: next-template
        build:
            context: .
        volumes:
            - .:/app
            - /app/node_modules
        command: yarn start:dev
        env_file:
            - .env
        ports:
            - "3000:3000"
        restart: always
volumes:
    app:
